---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  schemas:
    error_response:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              detail:
                type: string
              source:
                type: object
            required:
            - detail
      required:
      - errors
    customer:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              example: '1'
            type:
              type: string
              example: customer
            attributes:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                enterprise_id:
                  type: integer
                  example: 2
                first_name:
                  type: string
                  nullable: true
                  example: Alice
                last_name:
                  type: string
                  nullable: true
                  example: Springs
                code:
                  type: string
                  nullable: true
                  example: BUYER1
                email:
                  type: string
                  example: alice@example.com
                allow_charges:
                  type: boolean
                  example: false
                tags:
                  type: array
                  items:
                    type: string
                  example:
                  - staff
                  - discount
                terms_and_conditions_accepted_at:
                  type: string
                  format: date-time
                  nullable: true
                  example: '2022-03-12T15:55:00.000+11:00'
                billing_address:
                  type: object
                  nullable: true
                  example:
                shipping_address:
                  type: object
                  nullable: true
                  example:
                    phone: 0404 333 222 111
                    latitude: -37.8173751
                    longitude: 144.964803195704
                    first_name: Alice
                    last_name: Springs
                    street_address_1: 1 Flinders Street
                    street_address_2: ''
                    postal_code: '1234'
                    locality: Melbourne
                    region:
                      code: Vic
                      name: Victoria
                    country:
                      code: AU
                      name: Australia
              required:
              - id
              - enterprise_id
              - first_name
              - last_name
              - code
              - email
              - allow_charges
              - tags
              - terms_and_conditions_accepted_at
              - billing_address
              - shipping_address
            relationships:
              type: object
              properties:
                enterprise:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                          example: enterprise
                    links:
                      type: object
                      properties:
                        related:
                          type: string
        meta:
          type: object
        links:
          type: object
      required:
      - data
    customers_collection:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                example: '1'
              type:
                type: string
                example: customer
              attributes:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  enterprise_id:
                    type: integer
                    example: 2
                  first_name:
                    type: string
                    nullable: true
                    example: Alice
                  last_name:
                    type: string
                    nullable: true
                    example: Springs
                  code:
                    type: string
                    nullable: true
                    example: BUYER1
                  email:
                    type: string
                    example: alice@example.com
                  allow_charges:
                    type: boolean
                    example: false
                  tags:
                    type: array
                    items:
                      type: string
                    example:
                    - staff
                    - discount
                  terms_and_conditions_accepted_at:
                    type: string
                    format: date-time
                    nullable: true
                    example: '2022-03-12T15:55:00.000+11:00'
                  billing_address:
                    type: object
                    nullable: true
                    example:
                  shipping_address:
                    type: object
                    nullable: true
                    example:
                      phone: 0404 333 222 111
                      latitude: -37.8173751
                      longitude: 144.964803195704
                      first_name: Alice
                      last_name: Springs
                      street_address_1: 1 Flinders Street
                      street_address_2: ''
                      postal_code: '1234'
                      locality: Melbourne
                      region:
                        code: Vic
                        name: Victoria
                      country:
                        code: AU
                        name: Australia
                  balance:
                    type: number
                    format: double
                required:
                - id
                - enterprise_id
                - first_name
                - last_name
                - code
                - email
                - allow_charges
                - tags
                - terms_and_conditions_accepted_at
                - billing_address
                - shipping_address
              relationships:
                type: object
                properties:
                  enterprise:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          id:
                            type: string
                          type:
                            type: string
                            example: enterprise
                      links:
                        type: object
                        properties:
                          related:
                            type: string
        meta:
          type: object
          properties:
            pagination:
              type: object
              properties:
                results:
                  type: integer
                  example: 250
                pages:
                  type: integer
                  example: 5
                page:
                  type: integer
                  example: 2
                per_page:
                  type: integer
                  example: 50
          required:
          - pagination
        links:
          type: object
          properties:
            self:
              type: string
            first:
              type: string
            prev:
              type: string
              nullable: true
            next:
              type: string
              nullable: true
            last:
              type: string
      required:
      - data
      - meta
      - links
    customer_account_transaction:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              example: '1'
            type:
              type: string
              example: customer_account_transaction
            attributes:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                customer_id:
                  type: integer
                  example: 10
                amount:
                  type: decimal
                  example: 10.5
                currency:
                  type: string
                  example: AUD
                description:
                  type: string
                  nullable: true
                  example: Payment processed by POS
                balance:
                  type: decimal
                  example: 10.5
              required:
              - id
              - customer_id
              - amount
              - currency
              - description
              - balance
            relationships:
              type: object
              properties:
                customer:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                          example: customer
                    links:
                      type: object
                      properties:
                        related:
                          type: string
        meta:
          type: object
        links:
          type: object
      required:
      - data
  securitySchemes:
    api_key_header:
      type: apiKey
      name: X-Api-Token
      in: header
      description: Authenticates via API key passed in specified header
    api_key_param:
      type: apiKey
      name: token
      in: query
      description: Authenticates via API key passed in specified query param
    session:
      type: apiKey
      name: _ofn_session_id
      in: cookie
      description: Authenticates using the current user's session if logged in
paths:
  "/api/v1/customer_account_transaction":
    post:
      summary: Create customer transaction
      tags:
      - Customer account transaction
      parameters: []
      responses:
        '201':
          description: Customer transaction created
          content:
            application/json; charset=utf-8:
              examples:
                Customer transaction created:
                  value:
                    data:
                      id: '1'
                      type: customer_account_transaction
                      attributes:
                        id: 1
                        customer_id: 1
                        amount: '10.25'
                        currency: AUD
                        description: 'API credit: Payment processed by POS'
                        balance: '10.25'
            application/json:
              schema:
                "$ref": "#/components/schemas/customer_account_transaction"
        '422':
          description: Missing required parameter
          content:
            application/json; charset=utf-8:
              examples:
                Unpermitted parameter:
                  value:
                    errors:
                    - detail: 'Parameters not allowed in this request: id, created_by_id'
                Unprocessable entity:
                  value:
                    errors:
                    - detail: 'A required parameter is missing or empty: customer_account_transaction'
                Missing required parameter:
                  value:
                    errors:
                    - detail: Invalid resource. Please fix errors and try again.
                    meta:
                      validation_errors:
                      - Amount can't be blank
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '404':
          description: Invalid customer ID
          content:
            application/json; charset=utf-8:
              examples:
                Invalid customer ID:
                  value:
                    errors:
                    - detail: The resource you were looking for could not be found.
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '401':
          description: Unauthorized
          content:
            application/json; charset=utf-8:
              examples:
                Access forbidden:
                  value:
                    errors:
                    - detail: You are not authorized to perform that action.
                Unauthorized:
                  value:
                    errors:
                    - detail: You are not authorized to perform that action.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                  example: 10
                amount:
                  type: decimal
                  example: 10.5
                description:
                  type: string
                  nullable: true
                  example: Payment processed by POS
              required:
              - customer_id
              - amount
  "/api/v1/customers":
    get:
      summary: List customers
      tags:
      - Customers
      parameters:
      - name: enterprise_id
        in: query
        schema:
          type: string
      - name: extra_fields[customer]
        in: query
        example: balance
        description: Add extra fields to each customer
        schema:
          type: string
      responses:
        '200':
          description: Customers list
          content:
            application/json; charset=utf-8:
              examples:
                Customers list:
                  value:
                    data:
                    - id: '1'
                      type: customer
                      attributes:
                        id: 1
                        enterprise_id: 1
                        first_name: ''
                        last_name: ''
                        code: CUSTOMER1
                        email: nga@beckerprosacco.co.uk
                        allow_charges: false
                        terms_and_conditions_accepted_at: '2000-01-01T00:00:00.000+11:00'
                        tags:
                        - long-term
                        billing_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                        shipping_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                        balance: 0.0
                      relationships:
                        enterprise:
                          data:
                            id: '1'
                            type: enterprise
                          links:
                            related: http://test.host/api/v1/enterprises/1
                    - id: '2'
                      type: customer
                      attributes:
                        id: 2
                        enterprise_id: 1
                        first_name: ''
                        last_name: ''
                        code: CUSTOMER2
                        email: alissa@hintz.info
                        allow_charges: false
                        terms_and_conditions_accepted_at:
                        tags: []
                        billing_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                        shipping_address:
                        balance: 0.0
                      relationships:
                        enterprise:
                          data:
                            id: '1'
                            type: enterprise
                          links:
                            related: http://test.host/api/v1/enterprises/1
                    meta:
                      pagination:
                        results: 2
                        pages: 1
                        page: 1
                        per_page: 50
                    links:
                      self: http://test.host/api/v1/customers?enterprise_id=1&extra_fields%5Bcustomer%5D=balance&page=1
                      first: http://test.host/api/v1/customers?enterprise_id=1&extra_fields%5Bcustomer%5D=balance&page=1
                      prev:
                      next:
                      last: http://test.host/api/v1/customers?enterprise_id=1&extra_fields%5Bcustomer%5D=balance&page=1
            application/json:
              schema:
                "$ref": "#/components/schemas/customers_collection"
    post:
      summary: Create customer
      tags:
      - Customers
      parameters: []
      responses:
        '201':
          description: Example customer created
          content:
            application/json; charset=utf-8:
              examples:
                Minimal customer created:
                  value:
                    data:
                      id: '4'
                      type: customer
                      attributes:
                        id: 4
                        enterprise_id: 1
                        first_name: ''
                        last_name: ''
                        code:
                        email: test@example.com
                        allow_charges: false
                        terms_and_conditions_accepted_at:
                        tags: []
                        billing_address:
                        shipping_address:
                      relationships:
                        enterprise:
                          data:
                            id: '1'
                            type: enterprise
                          links:
                            related: http://test.host/api/v1/enterprises/1
                Example customer created:
                  value:
                    data:
                      id: '4'
                      type: customer
                      attributes:
                        id: 4
                        enterprise_id: 1
                        first_name: Alice
                        last_name: Springs
                        code: BUYER1
                        email: alice@example.com
                        allow_charges: false
                        terms_and_conditions_accepted_at:
                        tags:
                        - staff
                        - discount
                        billing_address:
                        shipping_address:
                          phone: 0404 333 222 111
                          latitude: -37.8173751
                          longitude: 144.964803195704
                          first_name: Alice
                          last_name: Springs
                          street_address_1: 1 Flinders Street
                          street_address_2: ''
                          postal_code: '1234'
                          locality: Melbourne
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                      relationships:
                        enterprise:
                          data:
                            id: '1'
                            type: enterprise
                          links:
                            related: http://test.host/api/v1/enterprises/1
            application/json:
              schema:
                "$ref": "#/components/schemas/customer"
        '422':
          description: Unprocessable entity
          content:
            application/json; charset=utf-8:
              examples:
                Unpermitted parameter:
                  value:
                    errors:
                    - detail: 'Parameters not allowed in this request: allow_charges'
                Unprocessable entity:
                  value:
                    errors:
                    - detail: 'A required parameter is missing or empty: customer'
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                enterprise_id:
                  type: integer
                  example: 2
                first_name:
                  type: string
                  nullable: true
                  example: Alice
                last_name:
                  type: string
                  nullable: true
                  example: Springs
                code:
                  type: string
                  nullable: true
                  example: BUYER1
                email:
                  type: string
                  example: alice@example.com
                tags:
                  type: array
                  items:
                    type: string
                  example:
                  - staff
                  - discount
                billing_address:
                  type: object
                  nullable: true
                  example:
                shipping_address:
                  type: object
                  nullable: true
                  example:
                    phone: 0404 333 222 111
                    latitude: -37.8173751
                    longitude: 144.964803195704
                    first_name: Alice
                    last_name: Springs
                    street_address_1: 1 Flinders Street
                    street_address_2: ''
                    postal_code: '1234'
                    locality: Melbourne
                    region:
                      code: Vic
                      name: Victoria
                    country:
                      code: AU
                      name: Australia
              required:
              - enterprise_id
              - email
  "/api/v1/customers/{id}":
    get:
      summary: Show customer
      tags:
      - Customers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Customer
          content:
            application/json; charset=utf-8:
              examples:
                Customer:
                  value:
                    data:
                      id: '1'
                      type: customer
                      attributes:
                        id: 1
                        enterprise_id: 1
                        first_name: ''
                        last_name: ''
                        code: CUSTOMER1
                        email: nga@beckerprosacco.co.uk
                        allow_charges: false
                        terms_and_conditions_accepted_at: '2000-01-01T00:00:00.000+11:00'
                        tags:
                        - long-term
                        billing_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                        shipping_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                        balance: 0.0
                      relationships:
                        enterprise:
                          data:
                            id: '1'
                            type: enterprise
                          links:
                            related: http://test.host/api/v1/enterprises/1
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: '1'
                      type:
                        type: string
                        example: customer
                      attributes:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          enterprise_id:
                            type: integer
                            example: 2
                          first_name:
                            type: string
                            nullable: true
                            example: Alice
                          last_name:
                            type: string
                            nullable: true
                            example: Springs
                          code:
                            type: string
                            nullable: true
                            example: BUYER1
                          email:
                            type: string
                            example: alice@example.com
                          allow_charges:
                            type: boolean
                            example: false
                          tags:
                            type: array
                            items:
                              type: string
                            example:
                            - staff
                            - discount
                          terms_and_conditions_accepted_at:
                            type: string
                            format: date-time
                            nullable: true
                            example: '2022-03-12T15:55:00.000+11:00'
                          billing_address:
                            type: object
                            nullable: true
                            example:
                          shipping_address:
                            type: object
                            nullable: true
                            example:
                              phone: 0404 333 222 111
                              latitude: -37.8173751
                              longitude: 144.964803195704
                              first_name: Alice
                              last_name: Springs
                              street_address_1: 1 Flinders Street
                              street_address_2: ''
                              postal_code: '1234'
                              locality: Melbourne
                              region:
                                code: Vic
                                name: Victoria
                              country:
                                code: AU
                                name: Australia
                          balance:
                            type: number
                            format: double
                        required:
                        - id
                        - enterprise_id
                        - first_name
                        - last_name
                        - code
                        - email
                        - allow_charges
                        - tags
                        - terms_and_conditions_accepted_at
                        - billing_address
                        - shipping_address
                        - balance
                      relationships:
                        type: object
                        properties:
                          enterprise:
                            type: object
                            properties:
                              data:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                                    example: enterprise
                              links:
                                type: object
                                properties:
                                  related:
                                    type: string
                  meta:
                    type: object
                  links:
                    type: object
                required:
                - data
        '404':
          description: Not found
          content:
            application/json; charset=utf-8:
              examples:
                Not found:
                  value:
                    errors:
                    - detail: The resource you were looking for could not be found.
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '401':
          description: Unauthorized
          content:
            application/json; charset=utf-8:
              examples:
                Unauthorized:
                  value:
                    errors:
                    - detail: You are not authorized to perform that action.
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
    put:
      summary: Update customer
      tags:
      - Customers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Customer updated
          content:
            application/json; charset=utf-8:
              examples:
                Customer updated:
                  value:
                    data:
                      id: '1'
                      type: customer
                      attributes:
                        id: 1
                        enterprise_id: 1
                        first_name: ''
                        last_name: ''
                        code: CUSTOMER1
                        email: test@example.com
                        allow_charges: false
                        terms_and_conditions_accepted_at: '2000-01-01T00:00:00.000+11:00'
                        tags:
                        - long-term
                        billing_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                        shipping_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                      relationships:
                        enterprise:
                          data:
                            id: '1'
                            type: enterprise
                          links:
                            related: http://test.host/api/v1/enterprises/1
            application/json:
              schema:
                "$ref": "#/components/schemas/customer"
        '422':
          description: Unprocessable entity
          content:
            application/json; charset=utf-8:
              examples:
                Unprocessable entity:
                  value:
                    errors:
                    - detail: 'A required parameter is missing or empty: customer'
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  nullable: true
                  example: Alice
                last_name:
                  type: string
                  nullable: true
                  example: Springs
                code:
                  type: string
                  nullable: true
                  example: BUYER1
                email:
                  type: string
                  example: alice@example.com
                tags:
                  type: array
                  items:
                    type: string
                  example:
                  - staff
                  - discount
                billing_address:
                  type: object
                  nullable: true
                  example:
                shipping_address:
                  type: object
                  nullable: true
                  example:
                    phone: 0404 333 222 111
                    latitude: -37.8173751
                    longitude: 144.964803195704
                    first_name: Alice
                    last_name: Springs
                    street_address_1: 1 Flinders Street
                    street_address_2: ''
                    postal_code: '1234'
                    locality: Melbourne
                    region:
                      code: Vic
                      name: Victoria
                    country:
                      code: AU
                      name: Australia
              required:
              - enterprise_id
              - email
    delete:
      summary: Delete customer
      tags:
      - Customers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Customer deleted
          content:
            application/json; charset=utf-8:
              examples:
                Customer deleted:
                  value:
                    data:
                      id: '1'
                      type: customer
                      attributes:
                        id: 1
                        enterprise_id: 1
                        first_name: ''
                        last_name: ''
                        code: CUSTOMER1
                        email: nga@beckerprosacco.co.uk
                        allow_charges: false
                        terms_and_conditions_accepted_at: '2000-01-01T00:00:00.000+11:00'
                        tags: []
                        billing_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                        shipping_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                      relationships:
                        enterprise:
                          data:
                            id: '1'
                            type: enterprise
                          links:
                            related: http://test.host/api/v1/enterprises/1
            application/json:
              schema:
                "$ref": "#/components/schemas/customer"
  "/api/v1/enterprises/{enterprise_id}/customers":
    get:
      summary: List customers of an enterprise
      tags:
      - Customers
      - Enterprises
      parameters:
      - name: enterprise_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Customers list
          content:
            application/json; charset=utf-8:
              examples:
                Customers list:
                  value:
                    data:
                    - id: '1'
                      type: customer
                      attributes:
                        id: 1
                        enterprise_id: 1
                        first_name: ''
                        last_name: ''
                        code: CUSTOMER1
                        email: nga@beckerprosacco.co.uk
                        allow_charges: false
                        terms_and_conditions_accepted_at: '2000-01-01T00:00:00.000+11:00'
                        tags:
                        - long-term
                        billing_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                        shipping_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                      relationships:
                        enterprise:
                          data:
                            id: '1'
                            type: enterprise
                          links:
                            related: http://test.host/api/v1/enterprises/1
                    - id: '2'
                      type: customer
                      attributes:
                        id: 2
                        enterprise_id: 1
                        first_name: ''
                        last_name: ''
                        code: CUSTOMER2
                        email: alissa@hintz.info
                        allow_charges: false
                        terms_and_conditions_accepted_at:
                        tags: []
                        billing_address:
                          phone: 123-456-7890
                          latitude:
                          longitude:
                          first_name: John
                          last_name: Doe
                          street_address_1: 10 Lovely Street
                          street_address_2: Northwest
                          postal_code: '20170'
                          locality: Herndon
                          region:
                            name: Victoria
                            code: Vic
                          country:
                            name: Australia
                            code: AU
                        shipping_address:
                      relationships:
                        enterprise:
                          data:
                            id: '1'
                            type: enterprise
                          links:
                            related: http://test.host/api/v1/enterprises/1
                    meta:
                      pagination:
                        results: 2
                        pages: 1
                        page: 1
                        per_page: 50
                    links:
                      self: http://test.host/api/v1/enterprises/1/customers?page=1
                      first: http://test.host/api/v1/enterprises/1/customers?page=1
                      prev:
                      next:
                      last: http://test.host/api/v1/enterprises/1/customers?page=1
            application/json:
              schema:
                "$ref": "#/components/schemas/customers_collection"
servers:
- url: "/"
